#!/usr/bin/python

'''
Given a string containing brackets [], braces {}, parentheses (), or any combination thereof, 
verify that any and all pairs are matched and nested correctly. Any other characters should be ignored. For example, 
"{what is (42)}?" is balanced and "[text}" is not.
'''

def is_paired(input_string):
    options = {
        ")" : "(",
        "]" : "[",
        "}" : "{"
    }
    stack = []
    for char in input_string:
        if char in '([{':
            stack.append(char)
        elif char in options:
            if len(stack) == 0 or stack.pop() != options[char]:
                return False

    return len(stack) == 0
