#!/usr/bin/python

import time
from playwright.sync_api import sync_playwright
import time


with sync_playwright() as playwright:

    webkit = playwright.webkit
    browser = webkit.launch(headless=False)
    page = browser.new_page()

    url = 'https://www.shmu.sk/sk/?page=1'
    page.goto(url)

    time.sleep(2)

    btn = page.get_by_role("hydro", name="Hydrologické spravodajstvo").check()
    btn.wait_for()  # Ensure the button is visible and ready
    btn.click()  # Click the button

        # Step 3: Wait for navigation or content to load
    page.wait_for_load_state('load')  # Wait for the page to load completely

    html_content = page.content()  # Get the full HTML content of the page
    print(html_content)


    time.sleep(1)

    browser.close()
