#!/usr/bin/python

'''
Given an age in seconds, calculate how old someone would be on a planet in our Solar System.

One Earth year equals 365.25 Earth days, or 31,557,600 seconds. If you were told someone was 1,000,000,000 seconds old, their age would be 31.69 Earth-years.

For the other planets, you have to account for their orbital period in Earth Years:

Planet	Orbital period in Earth Years
Mercury	0.2408467
Venus	0.61519726
Earth	1.0
Mars	1.8808158
Jupiter	11.862615
Saturn	29.447498
Uranus	84.016846
Neptune	164.79132
'''


class SpaceAge:
    planets = {
        "Mercury": 0.2408467,
        "Venus": 0.61519726,
        "Earth": 1.0,
        "Mars": 1.8808158,
        "Jupiter": 11.862615,
        "Saturn": 29.447498,
        "Uranus": 84.016846,
        "Neptune": 164.79132
    }
    def __init__(self, seconds):
        self.seconds = seconds
        for planet, ratio in self.planets.items():
            method_name = f"on_{planet.lower()}"
            setattr(self, method_name, self._create_method(planet, ratio))
    def _create_method(self, planet_name, ratio):
        def method():
            earth_years = self.seconds / 31557600
            return round(earth_years / ratio, 2)
        return method
        return method
